### ISSUE TITLE
exclude precision and scale from @Column for Double fields

### ISSUE THREAD

**Issue by schegolevalex** [patrodyne/hisrc-hyperjaxb#2]
According [this](https://stackoverflow.com/questions/76598641/patrodyne-hisrc-hyperjaxb-maven-plugin-exclude-precision-and-scale-from-column) question on stackoverflow please correct [DefaultCustomizations.xml](https://github.com/patrodyne/hisrc-hyperjaxb/blob/cb05285340b0f3ae29d5fddbac36195b39828d0e/ejb/plugin/src/main/resources/org/jvnet/hyperjaxb/ejb/strategy/customizing/impl/DefaultCustomizations.xml#L108) to exclude precision and scale property from `@Column` for `Double` fields.

**Comment by patrodyne** [comment]
[Release 2.1.1](https://github.com/patrodyne/hisrc-hyperjaxb/releases/tag/2.1.1) includes this commit [`9ee6d18`](https://github.com/patrodyne/hisrc-hyperjaxb/commit/9ee6d184fe273efd4a24921bbd40d5402a07885f#diff-42013543f18e6bde52afedd806adeb9921f1e25a7ad24f61d2e5759167332e79) to remove the `scale="10" precision="20"` attributes from the `xsd:float` and `xsd:double` customizations.

**Comment by schegolevalex** [comment]
thank you!
